{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "1738330b",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "from imblearn.ensemble import BalancedRandomForestClassifier\n",
    "from imblearn.over_sampling import RandomOverSampler \n",
    "import optuna\n",
    "from sklearn.model_selection import StratifiedKFold, train_test_split, cross_val_score\n",
    "from sklearn import datasets"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "b5bdacc1",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[32m[I 2021-08-17 12:44:07,703]\u001b[0m A new study created in memory with name: test\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Running fold number:  0\n",
      "89 89\n",
      "21 19\n",
      "running optuna in first fold\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[32m[I 2021-08-17 12:44:08,535]\u001b[0m Trial 0 finished with value: 0.550561797752809 and parameters: {'n_estimators': 597, 'max_depth': 19}. Best is trial 0 with value: 0.550561797752809.\u001b[0m\n",
      "\u001b[32m[I 2021-08-17 12:44:09,699]\u001b[0m Trial 1 finished with value: 0.550561797752809 and parameters: {'n_estimators': 806, 'max_depth': 7}. Best is trial 0 with value: 0.550561797752809.\u001b[0m\n",
      "\u001b[32m[I 2021-08-17 12:44:10,095]\u001b[0m Trial 2 finished with value: 0.5449438202247191 and parameters: {'n_estimators': 283, 'max_depth': 115}. Best is trial 0 with value: 0.550561797752809.\u001b[0m\n",
      "\u001b[32m[I 2021-08-17 12:44:10,137]\u001b[0m Trial 3 finished with value: 0.5674157303370786 and parameters: {'n_estimators': 26, 'max_depth': 30}. Best is trial 3 with value: 0.5674157303370786.\u001b[0m\n",
      "\u001b[32m[I 2021-08-17 12:44:11,033]\u001b[0m Trial 4 finished with value: 0.5393258426966292 and parameters: {'n_estimators': 648, 'max_depth': 9}. Best is trial 3 with value: 0.5674157303370786.\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "bested optuna params: {'n_estimators': 26, 'max_depth': 30}\n",
      "Running fold number:  1\n",
      "87 87\n",
      "23 17\n",
      "Running fold number:  2\n",
      "93 93\n",
      "17 23\n",
      "Running fold number:  3\n",
      "87 87\n",
      "23 17\n",
      "Running fold number:  4\n",
      "84 84\n",
      "26 14\n",
      "Running fold number:  5\n",
      "89 89\n",
      "21 19\n",
      "Running fold number:  6\n",
      "87 87\n",
      "23 17\n",
      "Running fold number:  7\n",
      "93 93\n",
      "17 23\n",
      "Running fold number:  8\n",
      "87 87\n",
      "23 17\n",
      "Running fold number:  9\n",
      "84 84\n",
      "26 14\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/imblearn/ensemble/_forest.py\", line 425, in fit\n",
      "    accept_sparse=\"csc\", dtype=DTYPE)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 803, in check_X_y\n",
      "    estimator=estimator)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 642, in check_array\n",
      "    % (array.ndim, estimator_name))\n",
      "ValueError: Found array with dim 3. Estimator expected <= 2.\n",
      "\n",
      "  FitFailedWarning)\n",
      "/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/imblearn/ensemble/_forest.py\", line 425, in fit\n",
      "    accept_sparse=\"csc\", dtype=DTYPE)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 803, in check_X_y\n",
      "    estimator=estimator)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 642, in check_array\n",
      "    % (array.ndim, estimator_name))\n",
      "ValueError: Found array with dim 3. Estimator expected <= 2.\n",
      "\n",
      "  FitFailedWarning)\n",
      "/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/imblearn/ensemble/_forest.py\", line 425, in fit\n",
      "    accept_sparse=\"csc\", dtype=DTYPE)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 803, in check_X_y\n",
      "    estimator=estimator)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 642, in check_array\n",
      "    % (array.ndim, estimator_name))\n",
      "ValueError: Found array with dim 3. Estimator expected <= 2.\n",
      "\n",
      "  FitFailedWarning)\n",
      "/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/imblearn/ensemble/_forest.py\", line 425, in fit\n",
      "    accept_sparse=\"csc\", dtype=DTYPE)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 803, in check_X_y\n",
      "    estimator=estimator)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 642, in check_array\n",
      "    % (array.ndim, estimator_name))\n",
      "ValueError: Found array with dim 3. Estimator expected <= 2.\n",
      "\n",
      "  FitFailedWarning)\n",
      "/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/imblearn/ensemble/_forest.py\", line 425, in fit\n",
      "    accept_sparse=\"csc\", dtype=DTYPE)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 803, in check_X_y\n",
      "    estimator=estimator)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 642, in check_array\n",
      "    % (array.ndim, estimator_name))\n",
      "ValueError: Found array with dim 3. Estimator expected <= 2.\n",
      "\n",
      "  FitFailedWarning)\n",
      "/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/imblearn/ensemble/_forest.py\", line 425, in fit\n",
      "    accept_sparse=\"csc\", dtype=DTYPE)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 803, in check_X_y\n",
      "    estimator=estimator)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 642, in check_array\n",
      "    % (array.ndim, estimator_name))\n",
      "ValueError: Found array with dim 3. Estimator expected <= 2.\n",
      "\n",
      "  FitFailedWarning)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/imblearn/ensemble/_forest.py\", line 425, in fit\n",
      "    accept_sparse=\"csc\", dtype=DTYPE)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 803, in check_X_y\n",
      "    estimator=estimator)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 642, in check_array\n",
      "    % (array.ndim, estimator_name))\n",
      "ValueError: Found array with dim 3. Estimator expected <= 2.\n",
      "\n",
      "  FitFailedWarning)\n",
      "/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/imblearn/ensemble/_forest.py\", line 425, in fit\n",
      "    accept_sparse=\"csc\", dtype=DTYPE)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 803, in check_X_y\n",
      "    estimator=estimator)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 642, in check_array\n",
      "    % (array.ndim, estimator_name))\n",
      "ValueError: Found array with dim 3. Estimator expected <= 2.\n",
      "\n",
      "  FitFailedWarning)\n",
      "/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/imblearn/ensemble/_forest.py\", line 425, in fit\n",
      "    accept_sparse=\"csc\", dtype=DTYPE)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 803, in check_X_y\n",
      "    estimator=estimator)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 642, in check_array\n",
      "    % (array.ndim, estimator_name))\n",
      "ValueError: Found array with dim 3. Estimator expected <= 2.\n",
      "\n",
      "  FitFailedWarning)\n",
      "/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/imblearn/ensemble/_forest.py\", line 425, in fit\n",
      "    accept_sparse=\"csc\", dtype=DTYPE)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 803, in check_X_y\n",
      "    estimator=estimator)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 642, in check_array\n",
      "    % (array.ndim, estimator_name))\n",
      "ValueError: Found array with dim 3. Estimator expected <= 2.\n",
      "\n",
      "  FitFailedWarning)\n",
      "/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/imblearn/ensemble/_forest.py\", line 425, in fit\n",
      "    accept_sparse=\"csc\", dtype=DTYPE)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 803, in check_X_y\n",
      "    estimator=estimator)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 642, in check_array\n",
      "    % (array.ndim, estimator_name))\n",
      "ValueError: Found array with dim 3. Estimator expected <= 2.\n",
      "\n",
      "  FitFailedWarning)\n",
      "/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/imblearn/ensemble/_forest.py\", line 425, in fit\n",
      "    accept_sparse=\"csc\", dtype=DTYPE)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 803, in check_X_y\n",
      "    estimator=estimator)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 642, in check_array\n",
      "    % (array.ndim, estimator_name))\n",
      "ValueError: Found array with dim 3. Estimator expected <= 2.\n",
      "\n",
      "  FitFailedWarning)\n",
      "/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/imblearn/ensemble/_forest.py\", line 425, in fit\n",
      "    accept_sparse=\"csc\", dtype=DTYPE)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 803, in check_X_y\n",
      "    estimator=estimator)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 642, in check_array\n",
      "    % (array.ndim, estimator_name))\n",
      "ValueError: Found array with dim 3. Estimator expected <= 2.\n",
      "\n",
      "  FitFailedWarning)\n",
      "/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/imblearn/ensemble/_forest.py\", line 425, in fit\n",
      "    accept_sparse=\"csc\", dtype=DTYPE)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 803, in check_X_y\n",
      "    estimator=estimator)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 642, in check_array\n",
      "    % (array.ndim, estimator_name))\n",
      "ValueError: Found array with dim 3. Estimator expected <= 2.\n",
      "\n",
      "  FitFailedWarning)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/imblearn/ensemble/_forest.py\", line 425, in fit\n",
      "    accept_sparse=\"csc\", dtype=DTYPE)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 803, in check_X_y\n",
      "    estimator=estimator)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 642, in check_array\n",
      "    % (array.ndim, estimator_name))\n",
      "ValueError: Found array with dim 3. Estimator expected <= 2.\n",
      "\n",
      "  FitFailedWarning)\n",
      "/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/imblearn/ensemble/_forest.py\", line 425, in fit\n",
      "    accept_sparse=\"csc\", dtype=DTYPE)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 803, in check_X_y\n",
      "    estimator=estimator)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 642, in check_array\n",
      "    % (array.ndim, estimator_name))\n",
      "ValueError: Found array with dim 3. Estimator expected <= 2.\n",
      "\n",
      "  FitFailedWarning)\n",
      "/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/imblearn/ensemble/_forest.py\", line 425, in fit\n",
      "    accept_sparse=\"csc\", dtype=DTYPE)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 803, in check_X_y\n",
      "    estimator=estimator)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 642, in check_array\n",
      "    % (array.ndim, estimator_name))\n",
      "ValueError: Found array with dim 3. Estimator expected <= 2.\n",
      "\n",
      "  FitFailedWarning)\n",
      "/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/imblearn/ensemble/_forest.py\", line 425, in fit\n",
      "    accept_sparse=\"csc\", dtype=DTYPE)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 803, in check_X_y\n",
      "    estimator=estimator)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 642, in check_array\n",
      "    % (array.ndim, estimator_name))\n",
      "ValueError: Found array with dim 3. Estimator expected <= 2.\n",
      "\n",
      "  FitFailedWarning)\n",
      "/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/imblearn/ensemble/_forest.py\", line 425, in fit\n",
      "    accept_sparse=\"csc\", dtype=DTYPE)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 803, in check_X_y\n",
      "    estimator=estimator)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 642, in check_array\n",
      "    % (array.ndim, estimator_name))\n",
      "ValueError: Found array with dim 3. Estimator expected <= 2.\n",
      "\n",
      "  FitFailedWarning)\n",
      "/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/imblearn/ensemble/_forest.py\", line 425, in fit\n",
      "    accept_sparse=\"csc\", dtype=DTYPE)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 803, in check_X_y\n",
      "    estimator=estimator)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 642, in check_array\n",
      "    % (array.ndim, estimator_name))\n",
      "ValueError: Found array with dim 3. Estimator expected <= 2.\n",
      "\n",
      "  FitFailedWarning)\n",
      "/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/imblearn/ensemble/_forest.py\", line 425, in fit\n",
      "    accept_sparse=\"csc\", dtype=DTYPE)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 803, in check_X_y\n",
      "    estimator=estimator)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 642, in check_array\n",
      "    % (array.ndim, estimator_name))\n",
      "ValueError: Found array with dim 3. Estimator expected <= 2.\n",
      "\n",
      "  FitFailedWarning)\n",
      "/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/imblearn/ensemble/_forest.py\", line 425, in fit\n",
      "    accept_sparse=\"csc\", dtype=DTYPE)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 803, in check_X_y\n",
      "    estimator=estimator)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 642, in check_array\n",
      "    % (array.ndim, estimator_name))\n",
      "ValueError: Found array with dim 3. Estimator expected <= 2.\n",
      "\n",
      "  FitFailedWarning)\n",
      "/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/imblearn/ensemble/_forest.py\", line 425, in fit\n",
      "    accept_sparse=\"csc\", dtype=DTYPE)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 803, in check_X_y\n",
      "    estimator=estimator)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 642, in check_array\n",
      "    % (array.ndim, estimator_name))\n",
      "ValueError: Found array with dim 3. Estimator expected <= 2.\n",
      "\n",
      "  FitFailedWarning)\n",
      "/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/imblearn/ensemble/_forest.py\", line 425, in fit\n",
      "    accept_sparse=\"csc\", dtype=DTYPE)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 803, in check_X_y\n",
      "    estimator=estimator)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 642, in check_array\n",
      "    % (array.ndim, estimator_name))\n",
      "ValueError: Found array with dim 3. Estimator expected <= 2.\n",
      "\n",
      "  FitFailedWarning)\n",
      "/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/imblearn/ensemble/_forest.py\", line 425, in fit\n",
      "    accept_sparse=\"csc\", dtype=DTYPE)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 803, in check_X_y\n",
      "    estimator=estimator)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 642, in check_array\n",
      "    % (array.ndim, estimator_name))\n",
      "ValueError: Found array with dim 3. Estimator expected <= 2.\n",
      "\n",
      "  FitFailedWarning)\n",
      "/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/imblearn/ensemble/_forest.py\", line 425, in fit\n",
      "    accept_sparse=\"csc\", dtype=DTYPE)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 803, in check_X_y\n",
      "    estimator=estimator)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 642, in check_array\n",
      "    % (array.ndim, estimator_name))\n",
      "ValueError: Found array with dim 3. Estimator expected <= 2.\n",
      "\n",
      "  FitFailedWarning)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/imblearn/ensemble/_forest.py\", line 425, in fit\n",
      "    accept_sparse=\"csc\", dtype=DTYPE)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 803, in check_X_y\n",
      "    estimator=estimator)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 642, in check_array\n",
      "    % (array.ndim, estimator_name))\n",
      "ValueError: Found array with dim 3. Estimator expected <= 2.\n",
      "\n",
      "  FitFailedWarning)\n",
      "/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/imblearn/ensemble/_forest.py\", line 425, in fit\n",
      "    accept_sparse=\"csc\", dtype=DTYPE)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 803, in check_X_y\n",
      "    estimator=estimator)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 642, in check_array\n",
      "    % (array.ndim, estimator_name))\n",
      "ValueError: Found array with dim 3. Estimator expected <= 2.\n",
      "\n",
      "  FitFailedWarning)\n",
      "/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/imblearn/ensemble/_forest.py\", line 425, in fit\n",
      "    accept_sparse=\"csc\", dtype=DTYPE)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 803, in check_X_y\n",
      "    estimator=estimator)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 642, in check_array\n",
      "    % (array.ndim, estimator_name))\n",
      "ValueError: Found array with dim 3. Estimator expected <= 2.\n",
      "\n",
      "  FitFailedWarning)\n",
      "/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/imblearn/ensemble/_forest.py\", line 425, in fit\n",
      "    accept_sparse=\"csc\", dtype=DTYPE)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 803, in check_X_y\n",
      "    estimator=estimator)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/matthewvowels/GitHub/PhD_part_1/anaconda3/envs/my-torch/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 642, in check_array\n",
      "    % (array.ndim, estimator_name))\n",
      "ValueError: Found array with dim 3. Estimator expected <= 2.\n",
      "\n",
      "  FitFailedWarning)\n"
     ]
    }
   ],
   "source": [
    "\n",
    "diabetes = datasets.load_diabetes()\n",
    "X = diabetes.data[:200]\n",
    "y = np.round(np.random.uniform(0,1, 200))\n",
    "\n",
    "seed = 42\n",
    "n_splits = 5\n",
    "n_splits_nested = 2\n",
    "n_trials = 5\n",
    "\n",
    "class oversampled_Kfold():\n",
    "    def __init__(self, n_splits, random_state, n_repeats=1):\n",
    "        self.n_splits = n_splits\n",
    "        self.n_repeats = n_repeats\n",
    "        self.random_state = random_state\n",
    "\n",
    "    def split(self, X, y):\n",
    "        splits = np.array_split(np.random.choice(len(X), len(X),replace=False), self.n_splits)\n",
    "        train, test = [], []\n",
    "        for repeat in range(self.n_repeats):\n",
    "            for fold in range(len(splits)):\n",
    "                train_splits = splits[:]\n",
    "                test_splits = train_splits.pop(fold)\n",
    "                ros = RandomOverSampler(random_state=self.random_state)\n",
    "                train_idx = np.concatenate(train_splits)\n",
    "                Xidx_r, y_r = ros.fit_resample(train_idx.reshape(-1, 1), y[train_idx])\n",
    "                train.append(Xidx_r.flatten())\n",
    "                test.append(test_splits)\n",
    "        return list(zip(train, test))\n",
    "\n",
    "# output = cross_validate(clf,x,y, scoring=metrics,cv=rkf)\n",
    "\n",
    "\n",
    "def objective(trial):\n",
    "    n_estimators = trial.suggest_int(\"n_estimators\", 10, 1000)\n",
    "    max_depth = trial.suggest_int(\"max_depth\", 2, 500, log=True)\n",
    "    trial_config = {'n_estimators': n_estimators, 'max_depth': max_depth}\n",
    "    \n",
    "    \n",
    "    model = BalancedRandomForestClassifier(**trial_config)\n",
    "\n",
    "    score = cross_val_score(model, X_train, y_train, n_jobs=-1, cv=n_splits_nested)\n",
    "    accuracy = score.mean()\n",
    "    return accuracy\n",
    "\n",
    "\n",
    "kf = oversampled_Kfold(n_splits=5, random_state=42, n_repeats=2)\n",
    "\n",
    "kf_ = kf.split(X, y)\n",
    "\n",
    "f = 0\n",
    "preds = []\n",
    "probs = []\n",
    "GTs = []\n",
    "for train_index, test_index in kf_:\n",
    "    print('Running fold number: ', f)\n",
    "    \n",
    "    X_train, X_test = X[train_index], X[test_index]\n",
    "    y_train, y_test = y[train_index], y[test_index]\n",
    "    print((y_train == 0).sum(), (y_train==1).sum())\n",
    "    print((y_test == 0).sum(), (y_test==1).sum())\n",
    "    if f == 0: \n",
    "        print('running optuna in first fold')\n",
    "        study = optuna.create_study(study_name='test', direction='maximize')\n",
    "        study.optimize(objective, n_trials=n_trials)\n",
    "        config = study.best_trial.params\n",
    "        print('bested optuna params:' , config)\n",
    "        \n",
    "    model = BalancedRandomForestClassifier(**config)\n",
    "    model.fit(X_train, y_train)\n",
    "    preds.append(model.predict(X_test))\n",
    "    probs.append(model.predict_proba(X_test))\n",
    "    GTs.append(y_test)\n",
    "    f += 1\n",
    "        \n",
    "preds = np.concatenate(preds)\n",
    "probs = np.concatenate(probs)\n",
    "GTs = np.concatenate(GTs)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "590b519f",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9d1f7f4d",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b8184559",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
